# Site settings
title: Wumuja.blog
email: ''
description: > # this means to ignore newlines until "baseurl:"
  ''
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.wumuja.com" # the base hostname & protocol for your site
twitter_username: wumuaj
github_username:  ''

# Build settings
markdown: kramdown
